name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
      - '.github/workflows/**'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test Package
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 8.4, 8.3 ]
        stability: [ prefer-lowest, prefer-stable ]
        include:
          - php: 8.3
            laravel: 10.*
            testbench: 8.*
          - php: 8.4
            laravel: 11.*
            testbench: 9.*

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install system dependencies
      - name: Install system dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          apt-get update
          apt-get install -y libmagickwand-dev

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, mbstring, pcntl, pdo, sqlite3, bcmath, imagick

      # Verify PHP version and extensions
      - name: Verify PHP setup
        run: |
          php -v
          php -m

      # Cache Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ matrix.stability }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-

      # Install dependencies
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      # List installed Composer dependencies
      - name: List Installed Dependencies
        run: composer show -D

      # Run tests
      - name: Run Tests
        run: vendor/bin/pest --ci
